[key_bindings]
    AUTOCLEAR = "c"
    CANCEL = "esc"
    ENTER = "enter"
    FILTER = ["F4", "\\"]
    FOLLOW_ROW = "F"
    HELP = ["F1", "?"]
    MOVE_DOWN = ["down", "j"]
    MOVE_DOWN_STEP = "F11"
    MOVE_END = "end"
    MOVE_HOME = "home"
    MOVE_LEFT = ["left", "h"]
    MOVE_RIGHT = ["right", "l"]
    MOVE_UP = ["up", "k"]
    MOVE_UP_STEP = "F12"
    NEXT_SORT = ">"
    PREVIOUS_SORT = "<"
    PRIORITY_DOWN = ["F8", "J"]
    PRIORITY_UP = ["F7", "K"]
    QUIT = ["F10", "q"]
    REMOVE_ASK = ["d", "del", "F9"]
    RETRY = "r"
    RETRY_ALL = "R"
    REVERSE_SORT = "I"
    SEARCH = ["F3", "/"]
    SELECT_SORT = "F6"
    SETUP = "F2"
    TOGGLE_EXPAND_COLLAPSE = "x"
    TOGGLE_EXPAND_COLLAPSE_ALL = "X"
    TOGGLE_RESUME_PAUSE = ["p", "space"]
    TOGGLE_RESUME_PAUSE_ALL = "P"
    TOGGLE_SELECT = "s"
    UN_SELECT_ALL = "v"
    ADD_DOWNLOADS = "a"
