#!/bin/sh

# source xinitrc.d scripts
for f in /etc/X11/xinit/xinitrc.d/?*.sh; do [ -x "$f" ] && . "$f"; done
unset f

# merge xresources
xrdb -merge ~/.config/X11/xresources

# disable bell
xset -b

# lock after 600 seconds of inactivity
xset s 600

# disable screen blanking
xset dpms 0 0 0

# set keyboard/mouse remaps configurations
remaps &

# startup dunst
dunst-init &

# run some programs and services via runit's runsvdir
# stuff like pulseaudio, mpd, aria2, transmission, dwmbar, stalonetray, etc.
runsvdir -P "$USVDIR" &

# set wallpaper
wall () {
    feh --no-fehbg --bg-fill ~/.local/share/wall/$1
}
wall main.png || wall artix.png

# lock the screen
(sleep 0.2; lock) &

# loop to launch dwm and relaunch if killed
while true; do
    dwm
done
