#!/bin/sh

# set some paths
xinit="/etc/X11/xinit"
sysresources="$xinit/.Xresources"
sysmodmap="$xinit/.Xmodmap"
userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$HOME/.Xmodmap"

# merge in defaults and keymaps
[ -f "$sysresources" ]  && xrdb -merge $sysresources
[ -f "$sysmodmap" ]     && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ]    && xmodmap "$usermodmap"

# source xinitrc.d scripts
if [ -d "$xinit/xinitrc.d" ]; then
    for f in "$xinit"/xinitrc.d/?*.sh; do [ -x "$f" ] && . "$f"; done
    unset f
fi

# set my key remaps and other xset arguments
remaps &

# disable bell
xset -b &

# auto locking
xss-lock slock & # set locker to slock
xset s 600 # lock after 600 seconds of inactivity

# disable screen blanking
xset dpms 0 0 0 &

# run some programs and services via runit's runsvdir
# stuff like pulseaudio, mpd, aria2, transmission, dwmbar, stalonetray, etc.
runsvdir -P "$USVDIR" &

# set wallpaper
wall () {
    feh --no-fehbg --bg-fill ~/.local/share/wall/$1
}
wall main.png || wall artix.png

# lock the screen
(sleep 0.2; lock) &

# =====================
# = Window Manager
# =====================

# loop to launch dwm and relaunch if killed
while true; do
    dwm
done
