#!/bin/sh
exec >/dev/null 2>&1
jellyfin_conf=/etc/conf.d/jellyfin
export $(grep -v '^#' "$jellyfin_conf" | xargs)
exec chpst -u jellyfin:jellyfin /usr/bin/dotnet /usr/lib/jellyfin/jellyfin.dll --datadir ${JELLYFIN_DATA_DIRECTORY} --cachedir ${JELLYFIN_CACHE_DIRECTORY} ${JELLYFIN_ADD_OPTS}
