#!/bin/sh
# this script which is called by sxiv,
# shows info about the image in sxiv.
# $1: image, $2: image width, $3: image height
fs=' ][ '
exec 2>/dev/null
name=$(basename -- "$1")
size=$(du -Hh -- "$1" | cut -f 1)
geom="${2}x${3}"
tags=$(exiv2 -q pr -pi "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
tags=${tags%,}
echo "[ ${size}${fs}${geom}${tags:+$fs}${tags}${fs}${name} ]"
