#!/bin/sh
# sxiv's key handler script.

main()
{
    imgs="$(cat)" # get list of images from stdin
    first="$(imgs | head -n1)"
    count="$(imgs | wc -l)"

    case "$1" in
        h) help ;;
        w) wallpaper "$first" ;;
        W) wallpaper -s "$first" ;;
        g) args setsid -f gimp -- ;;
        p) args dprint ;;
        t) ask Trash &&
            args trash-put -- &&
            notif Trashed
            ;;
        d) ask Permanently Delete &&
            args rm -- &&
            notif Deleted
            ;;
        a) ask Autorotate &&
            jhead -autorot &&
            notif Autorotated
            ;;
        r) ask Rotate &&
            conv -rotate  90 &&
            notif Rotated
            ;;
        R) ask Rotate &&
            conv -rotate -90 &&
            notif Rotated
            ;;
        f) ask Flop &&
            conv -flop &&
            notif Flopped
            ;;
        y) xclip -selection clipboard -t \
            "$(file -b --mime-type "$first")" "$first" &&
            n -i "$first" "Copied to clipboard."
            ;;
    esac
}

ask() { dmenu-prompt "$* $count images?" ;}
args() { imgs | xargs -d'\n' "$@" ;}
conv() { imgs | xargs -I{} convert "$@" {} {} ;}
help() { notify-send 'sxiv key-handler help' "$(print_help)" ;}
imgs() { printf '%s\n' "$imgs" ;}

notif() {
    if [ "$1" = -i ]; then
        icon="$PWD/$(basename "$2")"
        shift 2
    fi
    notify-send -i "${icon:-none}" sxiv "$* $count images."
}

print_help() {
cat << 'eof'
y)   copy image to clipboard
a)   auto rotate based on metadata
r,R) rotate cw/ccw
f)   flip horizontally
g)   open in gimp
p)   print
w)   set as wallpaper
W)   set as wallpaper, no pywal
t)   trash
d)   permanently delete
h)   show this help message
eof
}

main "$@"
exit
