#!/bin/sh

# Config
path=/mnt/zramfs
# Use G for gigabytes, M for megabytes
swap_size=1536M
dir_size=1G
[ -r conf ] && . ./conf
swap_size="$conf_zramswap_size"
dir_size="$conf_zramdir_size"

# load zram kernel module
modprobe zram

# set compression to zstd (lz4 is also good)
echo zstd         > /sys/block/zram0/comp_algorithm
# set size
echo "$swap_size" > /sys/block/zram0/disksize

# enable it as swap.
mkswap --label zram0  /dev/zram0 2>&1
swapon --priority 100 /dev/zram0 2>&1

# create another zram block and save it's number
num="$(cat /sys/class/zram-control/hot_add)"

# do it's settings
echo zstd        > "/sys/block/zram${num}/comp_algorithm"
echo "$dir_size" > "/sys/block/zram${num}/disksize"

# make an ext4 filesystem in there
mke2fs -v -t ext4 "/dev/zram${num}"

# mount it
mkdir -p "$path"
mount --verbose --types ext4 -o "rw,noatime" "/dev/zram${num}" "$path"

# ownership
chown -R koonix:wheel "$path"

exec pause
